Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.cpus = 1
  end

  config.vm.define "mysql" do |mysql|
    mysql.vm.network "forwarded_port", guest: 3306, host: 3306
    mysql.vm.network "public_network", ip: "192.168.15.100"

    mysql.vm.provider "virtualbox" do |vb|
      vb.name = "ubuntu_mysql"
    end

    mysql.vm.provision "shell",
      inline: "sudo apt-get update"
      
    mysql.vm.provision "shell",
     inline: "sudo apt-get install -y mysql-server-5.7"

    mysql.vm.provision "shell",
      inline: "cat /vagrant/config/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys"
  end

end